version: '3.3'


services:
  backend:
    build:
      context: .
      dockerfile: fastapi_jinja2/Dockerfile
#    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0 --port 8000'
    volumes:
      - ./fastapi_jinja2:/fastapi_jinja2
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fastapi_jinja2:fastapi_jinja2@db:5432/fastapi_jinja2
    depends_on:
      - db


  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=fastapi_jinja2
      - POSTGRES_PASSWORD=fastapi_jinja2
      - POSTGRES_DB=fastapi_jinja2

volumes:
  postgres_data:

#
#
#  redis_city:
#    image: redis:6.2.4-alpine
#    container_name: 'redis'
#    expose:
#     - "6379"
#    volumes:
#      - ./redis_city/data:/data
#      - ./redis_city/redis.conf:/usr/local/etc/redis/redis.conf
#    command: redis-server /usr/local/etc/redis/redis.conf
#
#
#volumes:
#  redis_city: